### PR TITLE
OCPBUGS-17286,OCPCLOUD-2222: Merge https://github.com/kubernetes-sigs/cluster-api:v1.5.2 (3290c5a) into master

### PR DESCRIPTION
**Pull request by damdo**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Rebase looks fine, wondering though, should we squash down a bunch of the commits, we basically have setup, and then a bunch of tweaks to the setup, which I don't really need to care about the history of, WDYT?

**Comment by damdo** [comment]
/hold
For manual testing

**Comment by damdo** [comment]
Waiting on the Hypershift fix https://github.com/openshift/hypershift/pull/3087 to ~merge~ be contained in a CI image.

**Comment by JoelSpeed** [comment]
/retitle OCPBUGS-17286,[OCPCLOUD-2222](https://issues.redhat.com//browse/OCPCLOUD-2222): Merge https://github.com/kubernetes-sigs/cluster-api:v1.5.2 (3290c5a) into master

**Pull request merged**
