### PR TITLE
Rebase to cluster-api 0.0.0-alpha.4

### PR DESCRIPTION
**Pull request by ingvagabund**
**What this PR does / why we need it**:

Rebase to sigs.k8s.io/cluster-api@26aa37ad8bcffd5b69e2a514b5e9a8ac30744134 revision.
Opening the PR against `openshift-4.0-cluster-api-0.0.0-alpha.4` branch to have a clean rebase with all our carry commits on top of the latest upstream master HEAD.

Drops:
https://github.com/openshift/cluster-api/commit/3fc0ac858582aa486444faba589d9123dc3a9ed8
https://github.com/openshift/cluster-api/commit/0ca0637744dce4876e4ff64c458e7b3f0773e843

### CODE REVIEW

**Comment by ingvagabund** [comment]
/hold
Until we start running the CI over the new branch

**Comment by frobware** [comment]
new branch, no consumers yet, so

/approve

**Comment by enxebre** [comment]
Updated description:
This drops:
3fc0ac8
0ca0637

**Pull request merged**
