### PR TITLE
UPSTREAM: <carry>: openshift: Enable patching machines

### PR DESCRIPTION
**Pull request by enxebre**
This is a first step to move the responsibility for updating the machine/status up to the machine controller so no need to duplicate the logic across providers.
This gives more control over reconciling loops and when to requeue consistently across providers.
https://github.com/openshift/cluster-api-provider-azure/pull/93
https://github.com/openshift/cluster-api-provider-aws/pull/275
Eventually this should be baked in the interface with an struct returning the values to be mutated

Follow ups:
Move machine/machineSet controller into machine API operator repo
Remove `cluster` object references 
Consider introducing a `generationPredicate`

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Review by bison — COMMENTED** [review]
I don't understand splitting out `patchMachine()` from `setPhase()`. Now we needlessly patch both the spec and the status, and we have to keep track of this deep copy of the original Machine object to pass around, which seems error prone and problematic in any case where we don't return immediately after a patch.

**Comment by bison** [comment]
> I don't understand splitting out patchMachine() from setPhase(). Now we needlessly patch both the spec and the status, and we have to keep track of this deep copy of the original Machine object to pass around, which seems error prone and problematic in any case where we don't return immediately after a patch.

Sorry, never mind. I was missing the fact that we're intending to stop doing updates in the actuators, so the calls into the actuator are mutating the Machine and `patchMachine()` is submitting those changes.

**Review by bison — APPROVED** [review]
/approve
/lgtm

**Comment by enxebre** [comment]
closing as per Please see https://github.com/openshift/cluster-api#warning

**Pull request closed without merging**
