### PR TITLE
UPSTREAM: <carry>: openshift: skip the node drain if the node does not exist

### PR DESCRIPTION
**Pull request by cynepco3hahue**
**What this PR does / why we need it**:
On the machine deletion possible the situation when the update of the machine fails and finalizer wasn't removed from the machine, so it will reconcile with error, but on the next loop it will fail to fetch node under the drain method and it will continue forever. To avoid this we will skip the drain operation if the node already does not exist.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by enxebre** [comment]
This is an anomaly which seems safe to required manual verification when it happens. As an admin you can use `ExcludeNodeDrainingAnnotation`

**Comment by cynepco3hahue** [comment]
@enxebre We have e2e tests that fail because of it, also I do not sure at all that machine-controller is a good place to drain nodes, we have additional groups that work on the maintenance and draining controllers for the bare metal machines.

**Comment by enxebre** [comment]
can you link the specific tests failing for that reason? are those failing consistently because of this? if so then it's likely to be a symptom for a different problem as the expectation is not for this to happen

**Comment by cynepco3hahue** [comment]
@enxebre For example here I am waiting for the machine deletion https://github.com/openshift/cluster-api-actuator-pkg/blob/acbcbdc39cb8052eaafe69f8faa575e5d991aee4/pkg/e2e/machinehealthcheck/machinehealthcheck.go#L47
but the machine will stay here forever, and it will affect other tests machine set tests, because it expected to specific number of machines, but got expected+1

**Comment by ingvagabund** [comment]
> This is an anomaly which seems safe to required manual verification when it happens. As an admin you can use ExcludeNodeDrainingAnnotation

`ExcludeNodeDrainingAnnotation` is used for cases where we want to avoid draining an existing node before a machine gets deleted. Though, if the underlying node does not exist, there is nothing to drain. There are various reasons for a node to be in an non-existing state. E.g. the node got removed by an accident, the node got removed by other controller. This or that, the node daemon has to re-register itself. Yet still, if we are deleting a machine we don't need a node to re-register itself. The only drawback is the node will not get drained before it's physical instance is removed.

**Comment by ingvagabund** [comment]
/approve cancel

After additional investigation of failing HC tests, this does not seem to be the cause of the failures.

**Comment by cynepco3hahue** [comment]
@ingvagabund I think both problems exist, one under the HC and the second this one.

**Comment by ingvagabund** [comment]
> @ingvagabund I think both problems exist, one under the HC and the second this one.

This is definitely addressing another use case. Though, we will not merge any changes that are not addressing blocking or critical bugs. Until the feature/devel freeze is unfrozen.

**Comment by cynepco3hahue** [comment]
@ingvagabund Can we leave this PR until the unfrozen will happen?

**Comment by ingvagabund** [comment]
Yeah, it's fine to keep it open.

**Comment by cynepco3hahue** [comment]
@ingvagabund @enxebre Can we merge this one?

**Comment by ingvagabund** [comment]
We no longer push changes into the master branch. Please, change the target branch to be https://github.com/openshift/cluster-api/tree/openshift-4.0-cluster-api-0.0.0-alpha.4 instead. The PR is already merged for `openshift-4.2-cluster-api-0.1.0` here: https://github.com/openshift/cluster-api/pull/43.

**Comment by cynepco3hahue** [comment]
@ingvagabund hm ok, 4.2 is good for me, but next time you can ask from me to put it under the specific branch

**Pull request closed without merging**
