### PR TITLE
openshift: install dep and bazel in CI system

### PR DESCRIPTION
**Pull request by paulfantom**
Download bazel and dep before running unit tests.

### CODE REVIEW

**Comment by ingvagabund** [comment]
Super cool. Let's use it to verify it works and both bazel/dep verify part are run. Once all green, let's move the commands into the Prow job instead. Otherwise, this will get removed during rebase, resp. might cause merge conflicts.

/hold

**Comment by frobware** [comment]
> Super cool. Let's use it to verify it works and both bazel/dep verify part are run. Once all green, let's move the commands into the Prow job instead. Otherwise, this will get removed during rebase, resp. might cause merge conflicts.

Yes, on reflection, this sounds like a better approach.

**Comment by paulfantom** [comment]
Closing as this is already merged in CI pipeline (https://github.com/openshift/release/pull/2801)

**Pull request closed without merging**
