### PR TITLE
OCPBUGS-8487: Merge https://github.com/kubernetes-sigs/cluster-api:release-1.3 (eb18352) into master

### PR DESCRIPTION
**Pull request by damdo**
This PR merges upstream's https://github.com/kubernetes-sigs/cluster-api:release-1.3 (eb18352) into `master`.

Check [this comment](https://github.com/openshift/cluster-capi-operator/pull/101#issue-1564195291) for this CAPI provider bump testing status.

### CODE REVIEW

**Comment by damdo** [comment]
Testing things out here

/hold

**Comment by damdo** [comment]
For coordination with other CAPI components:

/hold

**Review by elmiko — COMMENTED** [review]
/lgtm

**Review by JoelSpeed — COMMENTED** [review]
/approve

**Comment by enxebre** [comment]
/hold
I'd like to gate on a hypershift test here, can this wait until Monday?

**Comment by damdo** [comment]
The`e2e-aws-serial` already passed here with the same commit: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api/167/pull-ci-openshift-cluster-api-master-e2e-aws-serial/1622668730611798016

**Comment by damdo** [comment]
This is a techpreview feature and it's actually not enabled on serial tests.
That's why we think we can override this job.

/override ci/prow/e2e-aws-serial

**Comment by damdo** [comment]
The Hypershift team, which also uses this fork, [has recently added](https://github.com/openshift/release/pull/36736) an hypershift-e2e test to run as an optional presubmit on PRs in this fork.
Since the [hypeshift-e2e](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api/167/pull-ci-openshift-cluster-api-master-e2e-hypershift/1632725753386766336) is now passing we are going ahead and unholding the PR.

/unhold

**Pull request merged**
