### PR TITLE
UPSTREAM: <carry>: openshift: Remove node controller from manager

### PR DESCRIPTION
**Pull request by enxebre**
Originally the logic for setting the nodeRef in a machine was split between the cluster-api node controller and opt-int external tooling that would set an annotation for the former controller to watch. There's no reason for this to keep leaving in two different places, furthermore the cluster-api node controller is deprecated. This unify this logic in one single nodelink controller, see https://github.com/openshift/machine-api-operator/pull/336

### CODE REVIEW

**Comment by enxebre** [comment]
/hold
needs openshift/machine-api-operator#336

**Comment by enxebre** [comment]
openshift/machine-api-operator#336 is merged
e2e testing via https://github.com/openshift/cluster-api-provider-aws/pull/232

**Comment by vikaschoudhary16** [comment]
testing success via https://github.com/openshift/cluster-api-provider-aws/pull/233.
/lgtm

**Pull request merged**
