### PR TITLE
UPSTREAM: <carry>: Add vendor to tools

### PR DESCRIPTION
**Pull request by alexander-demicev**
Add vendor to tools, seems like its failing `make test` in CI. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/22081/rehearse-22081-pull-ci-openshift-cluster-api-master-unit/1455945689346347008

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
just curious, is it possible to run with one of these options from the output log?

```
To ignore the vendor directory, use -mod=readonly or -mod=mod.
```

**Comment by alexander-demicev** [comment]
@elmiko I don't think it is possible, I'm assuming prow runs jobs with go modules only

**Comment by enxebre** [comment]
just FYI It's the image you are using which has -mod=readonly as an env variable https://github.com/openshift/release/blob/c32756180704c239f76063c8d39bc464ea7d2374/clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.16/Dockerfile#L14 so you have other alternatives if don't want to vendor, e.g https://github.com/openshift/release/pull/23206/files, though vendoring is fine.

**Comment by elmiko** [comment]
thanks for the extra detail @enxebre , if we are fine with the vendoring then i'm ok with it.
/lgtm

**Comment by alexander-demicev** [comment]
/hold 
I need to fix unit test job first

**Pull request merged**
