### PR TITLE
UPSTREAM: <carry>: openshift: Update Bazel WORKSPACE and build

### PR DESCRIPTION
**Pull request by michaelgugino**
WORKSPACE abd build/* were checked out from kubernetes/cluster-api:master

### CODE REVIEW

**Comment by michaelgugino** [comment]
/hold

This works for accomplishing the task locally, but the CI doesn't like it.  Need to sort out how to update CI's bazel

**Comment by eparis** [comment]
Is this still a PR we want to pursue or should we just close at this point?

**Comment by enxebre** [comment]
bazel was dropped in master now. I'd suggest we close this and if anything back port dropping bazel.

**Comment by enxebre** [comment]
Please see https://github.com/openshift/cluster-api#warning 
reopen against https://github.com/openshift/machine-api-operator if relevant.

**Pull request closed without merging**
