### PR TITLE
UPSTREAM: <carry>: openshift: Ensure delete continues w/o node

### PR DESCRIPTION
**Pull request by michaelgugino**
This commit ensures we can continue with the instance
and machine deletion in the case that the node
referenced by the machine is already deleted.

Nodes can potentially be deleted by administrators
or possibly in previous Reconcile loop of the
machine-controller that failed to properly update
annotations.

This commit also adds logging to be more uniform
with how we log errors elsewhere in the controller.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1713061
(cherry picked from commit a7df35547823323913f2a92bc0ed32f3d4fe90e1)

### CODE REVIEW

**Comment by frobware** [comment]
4.2 PR https://github.com/openshift/cluster-api/pull/43

**Comment by frobware** [comment]
/hold

Should this merge "today"? Or should it go into 4.1.z

**Comment by michaelgugino** [comment]
/hold
waiting for 4.1.z

**Comment by enxebre** [comment]
/hold
we need to renable CI here before merging

**Pull request merged**
