### PR TITLE
Copy drain lib from openshift/kubernetes-drain

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
**What this PR does / why we need it**:
machine controller reconcile logic uses drain lib from the openshift/kubernetes-drain repo. This repo does not have any owners and have no ci jobs running. In the recent past we have identified and fixed couple of issues in that lib. To improve productivity and resiliency, we want to embed this lib into cluster-api so that it is gated by CI and also we would own this code and that will help in reviewing and merging any fixes faster.
**context:**  https://github.com/openshift/kubernetes-drain/pull/4#issuecomment-519821627

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by bison** [comment]
Can we please have any description at all here? Where was this previously? Why are we copying it here now? etc.

**Comment by bison** [comment]
I see a binary `.swp` file in the diff that need to be deleted.

**Comment by vikaschoudhary16** [comment]
@bison done!!

**Comment by bison** [comment]
Thanks for adding the description. So, this brings the code into the repo, but we haven't changed the bits that depend on it. We're still importing the package from `openshift/kubernetes-drain`, right? Is that coming later, or am I missing something?

**Comment by vikaschoudhary16** [comment]
> Thanks for adding the description. So, this brings the code into the repo, but we haven't changed the bits that depend on it. We're still importing the package from `openshift/kubernetes-drain`, right? Is that coming later, or am I missing something?

You are right. I was planning to use it in the follow-up PR

**Review by bison — APPROVED** [review]
/lgtm

**Comment by enxebre** [comment]
For awareness it seems this PR sneaked in this patch https://github.com/openshift/kubernetes-drain/pull/4

**Pull request merged**
