### PR TITLE
OCPBUGS-6354,OCPBUGS-6372: Merge https://github.com/kubernetes-sigs/cluster-api:v1.4.2 (7b92ce4) into master

### PR DESCRIPTION
**Pull request by damdo**

### CODE REVIEW

**Comment by damdo** [comment]
/hold
for testing

**Comment by odvarkadaniel** [comment]
Is the hold needed here as of today? @damdo

**Comment by damdo** [comment]
Yes, we need to merge all the providers in short succession once they are all ready, then bump re-run the assets generation and merge https://github.com/openshift/cluster-capi-operator/pull/118

**Pull request merged**
