### PR TITLE
Rebase to v1.0.1

### PR DESCRIPTION
**Pull request by alexander-demicev**
This commit rebases the cluster-api openshift patches on top of the kubernetes-sigs/cluster-api master branch after.
There are several commits that we carry on top of the upstream cluster-api and the rebase process allows us to preserve those. Here is a description of the process I used to create this PR.

(replicated @elmiko's process within [openshift/kubernetes-autoscaler](https://github.com/openshift/kubernetes-autoscaler/pull/164))

Process

First we need to identify the carry commits that we currently have, this is done against our previous rebase (or fork in this case) to catch new changes. Once identified we will drop commits which have merged upstream and only carry unique commits. (see below for the carried and dropped commits).

Identify carry commits:
```
git log --oneline --no-merges 2887be851a4384bb000d2a498099f96fe0920cd1..ocp/master
```

where b4be01 is the last upstream commit in our fork. This is the
list of commits we will need to apply onto the new upstream version of the
cluster-api. ideally, some of these commits can be dropped.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch. The following commands cover these steps:
```
$ git remote update # make sure we update our refs
$ git checkout 2887be851a4384bb000d2a498099f96fe0920cd1 # release notes for 1.0.3 in this case
$ git checkout -b merge-tmp # create a temporary branch for our merge commit
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge latest upstream changes' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F - # create a new merge commit for our history
deadbeef12345678 # id of new merge commit
$ git branch rebase-upstream-latest deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout rebase-upstream-latest
$ git cherry-pick <carry commits> # cherry pick the needed commits into the new branch
```
With the rebase-upstream-latest branch in place, I cherry picked the carry commits which we should carry.

Carried Commits

These commits  are integral to our CI platform, or are specific to the releases we create for OpenShift.
```
52f0ec0e7 UPSTREAM: <carry>: Remove all upstream OWNERS
c525d5ccd UPSTREAM: <carry>: Update owners to reflect current team membership
6144f2ce6 UPSTREAM: <carry>: Add vendor to tools
beaafaf2f  UPSTREAM: <carry>: Add openshift specific changes
788312762 UPSTREAM: <carry>: Add vendor directory
8ed9e3750 UPSTREAM: <carry>: Remove .github directory
```

Changed Commits

```
---
```

Dropped Commits
```
---
```

### CODE REVIEW

**Comment by enxebre** [comment]
I'm confused, how can all those commits you mention in the description be dropped in this PR. I thought you dropped them here https://github.com/openshift/cluster-api/pull/143

**Comment by alexander-demicev** [comment]
@enxebre sorry, I updated the description, no dropped commits here.

**Pull request merged**
