### PR TITLE
WIP: Mirror alberto pr

### PR DESCRIPTION
**Pull request by ingvagabund**
DO NOT MERGED, just for debugging purposes

### CODE REVIEW

**Comment by ingvagabund** [comment]
Sometimes when I run the unit tests locally I see:
```
=== RUN   TestReconcile
E0130 15:09:25.997322   14974 controller.go:294] Unable to retrieve Machineset default/foo-74564b8d5f from store: MachineSet.machine.openshift.io "foo-74564b8d5f" not found
--- FAIL: TestReconcile (300.58s)
    machinedeployment_controller_test.go:146: timed out waiting reconcile error
```

I have suspicion there are no machinesets at all so the machine deployment actually does not lead to creation of machine sets. Still dunno why.

**Comment by enxebre** [comment]
closing in favour of https://github.com/openshift/cluster-api/pull/7

**Pull request closed without merging**
