### PR TITLE
Merge https://github.com/kubernetes-sigs/cluster-api:main into master

### PR DESCRIPTION
**Pull request by Fedosin**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
This PR doesn't look like it was created using the bot, I don't see a merge commit?

**Comment by Fedosin** [comment]
That PR was created using the bot: https://github.com/openshift/cluster-api/pull/162. Result is the same :( The problem is that we put too many unrelated commits in the rebase.

**Comment by Fedosin** [comment]
I'm working on manual rebase now, excluding all unnecessary commits from this list
```
0b5870f9c1316ae60d62b28ef846a93ff76cb6e4 - update docker go mod
8053946d9ebbad5be4da1e113212d87687f1fcd5 - ClusterClass: add MD variables to the ClusterClass proposal
53c1335b1c2f42a08fcc843729c6311b635c8079 - book: add TGIK ClusterClass video
7d5fa22b390b8723ea23b3142dc2ea5f764dc9a4 - Add HasPausedAnnotation and HasSkipRemediationAnnotation func deprecation notes to v1.0-v1.1 migration doc
249663da45c1e4702cec9e3e22c326f31c84b9ca - Remove generated names from error messages to reduce reconciliation
67b1665dfa76a1e86ebb65b9376d2d23eda72896 - handle error in case ownerRef is not set on crs binding
3c0d58bd0692ecd085df4b52303037e75f3d81bf - ClusterClass: fix YAMLs in proposal
83315e090752372a1531e77489ec5849d7bee883 - book: Add note about Kubernetes v1.23.{0-2} CRD issue and ClusterClass
64a3189840fdcf6c2e452c04001bbef93c201337 - allow KCP to Update when CoreDNS version doesn't change
5d31399f9ca5764af7a838c0d6f848f5c53c4235 - Upgrade to Kubernetes 1.23.3 in Quickstart and CI
57d8a98f505604b841c35ac605c8c2c5f0e7c919 - use kubebuilder envtest v1.23.3
b06431db6a5e8a95cc574ccfc44d8360fdb9629c - book: add Writing a ClusterClass doc
17bb94cf7098007e991d67d4b5a0232f24258d52 - fix review findings
10ec4dc711fb0b30b167464ea6e0d2d4d51bcb1a - fix review findings
776e481f13306c7241925a272d7473ba7fdaaafb - more review findings + additional fixes
2930a08fc00c6b31ddaad21cd2753ba0469cc13d - fix review finding
5f753223677e54099cf96e0bb740d7882bbbfc23 - reference CAPD quickstart ClusterClass
244585d6c86d5e0d431e35f50e9cf73ed6657ad5 - fix review findings
81cf1332c24e8713018e215d09464290f6520015 - topology plan command doc
312b64d7169a45565a279763622adf6daa240169 - book: make links in generate CRDS relative
699ae816e5801a5f9e9865ccc120b07a303f0c4e - Document how to change a ClusterClass
2f1b2829f1ee0c3f1c3d8aa40f8c9822464d7aa0 - simplified communication of CoreDNS compatibility
5246841905390ebf03abb94d64f1b68a118717f3 - book: Writing a ClusterClass: add ref example
7efd2b95b625fbc4f380f54109d96c2f8b483cde - Fix cert manager repo and add troubleshooting guide
147aa047e77bc0acdb3d28bf8241c83b85e72fdd - update clsuterctl version in e2e to latest patch
38370125bb731371ad3dc53d003a2f9833f849e6 - ClusterToInfrastructureMapFunc: Exclude externally managed infrastructures
de9eaae74e70a30f35e48c5f884ae92481389966 - Add note on where to find ClusterClass specific Cluster creation commands
85a5c85f3a38c0b072be4d2078df2ddc01761f95 - extend Operating a Managed Cluster doc
6177b6eb935a7608d5fcc0260d581b6fbd378b62 - seedling: Adding hetzner provider
5717dc4b5d03bdf424f0c9de36bf4d936cf9233d - allow provider specific infra machine template for upgrade tests
98f95891210d9d79189d502b5d15be5e03a51e77 - Support new control plane label and taint
abf682a46d932b39bfcb55f73ee8310605396f0c - :running: ClusterToInfrastructureMapFuncWithExternallyManagedCheck: Remove debugging leftovers
78700cf776e6f7e5ddd35308269aec303b06c2da - kcp: don't rollout machines when format is defaulted
7278d9d4ee97123dcd8c70b1a96d5cbe32f0c9fe - Update cert-manager links after migration
ef73bda280197b2412a1c959f3177d0577c0b3aa - Uplift controller runtime to v0.11.1
a5829fbe1fe1ac76f34d99140a7a5b3c0d999752 - Fix panics in conversions
4c367841a74d489a5226a6657b8c82868bcc346b - The old `1.0.x` wasn't matching the new version.
c655b11b84532c24536b81b7d0b4a7862a2519c5 - UPSTREAM: <carry>: Add openshift specific changes
8791881f54df0389f859a6f0c66a334ef0c499b6 - UPSTREAM: <carry>: Add vendor directory
```

**Pull request merged**
