### PR TITLE
Rebase latest upstream changes

### PR DESCRIPTION
**Pull request by alexander-demicev**
This commit rebases the cluster-api openshift patches on top of the kubernetes-sigs/cluster-api master branch after.
There are several commits that we carry on top of the upstream cluster-api and the rebase process allows us to preserve those. Here is a description of the process I used to create this PR.

(replicated @elmiko's process within [openshift/kubernetes-autoscaler](https://github.com/openshift/kubernetes-autoscaler/pull/164))

Process

First we need to identify the carry commits that we currently have, this is done against our previous rebase (or fork in this case) to catch new changes. Once identified we will drop commits which have merged upstream and only carry unique commits. (see below for the carried and dropped commits).

Identify carry commits:
```
git log --oneline --no-merges 2887be851a4384bb000d2a498099f96fe0920cd1..ocp/master
```

where b4be01 is the last upstream commit in our fork. This is the
list of commits we will need to apply onto the new upstream version of the
cluster-api. ideally, some of these commits can be dropped.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch. The following commands cover these steps:
```
$ git remote update # make sure we update our refs
$ git checkout 2887be851a4384bb000d2a498099f96fe0920cd1 # release notes for 1.0.3 in this case
$ git checkout -b merge-tmp # create a temporary branch for our merge commit
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge latest upstream changes' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F - # create a new merge commit for our history
deadbeef12345678 # id of new merge commit
$ git branch rebase-upstream-latest deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout rebase-upstream-latest
$ git cherry-pick <carry commits> # cherry pick the needed commits into the new branch
```
With the rebase-upstream-latest branch in place, I cherry picked the carry commits which we should carry.

Carried Commits

These commits  are integral to our CI platform, or are specific to the releases we create for OpenShift.
```
52f0ec0e7 UPSTREAM: <carry>: Remove all upstream OWNERS
c525d5ccd UPSTREAM: <carry>: Update owners to reflect current team membership
```

Changed Commits

```
---
```

Dropped Commits
```
b09907ac6 UPSTREAM: <carry>: openshift: deprecate master branch
9a3a7bbe9 UPSTREAM: <carry>: openshift: Change to use gofmt to honour go mod
9f7cdb9ca UPSTREAM: <carry>: openshift: Remove unused files
f616521f9 UPSTREAM: <carry>: openshift: Update Makefile for go modules and generate clients
8808011d8 UPSTREAM: <carry>: openshift: Revendor and migrate to go modules
c4a461a19 UPSTREAM: <carry>: openshift: Remove obsolete docs carried over from upstream
b2c5ded52 UPSTREAM: <carry>: openshift: Enable printcolumn for phase and move status to priority 1
2f02e328b UPSTREAM: <carry>: openshift: Disable metrics to avoid pod collisions
7a7a58ada UPSTREAM: <carry>: openshift: Drop bazelle/gazelle from Makefile
27007c841 UPSTREAM: <carry>: openshift: Drop bazel files
6112ef00d UPSTREAM: <carry>: openshift: Honour phases and fail appropiately
83f32d3e7 UPSTREAM: <carry>: openshift: pkg/drain: always honor pod termination timeout
baf569b39 UPSTREAM: <carry>: openshift: Regenerate clients after removing unused code
82f74b289 UPSTREAM: <carry>: openshift: Delete unused code
f389db466 UPSTREAM: <carry>: openshift: Revendor on cleaning up unused code
a45e8ab17 UPSTREAM: <carry>: openshift: Stop metrics on testing manager
81b81f8a3 UPSTREAM: <carry>: openshift: Update kubebuilder syntax to make controller tools happy and regenerate CRDs
4a41a950d UPSTREAM: <carry>: openshift: Change const name to satisfy kube-1.16.0
fefcf31a7 UPSTREAM: <carry>: openshift: Generate clients
6f865316a UPSTREAM: <carry>: openshift: Bump libraries to kube 1.16.0
655e2d6cc UPSTREAM: <carry>: openshift: Drop isDeleteAllowed func
0fff9684b UPSTREAM: <carry>: openshift: Run 'make goimports'
42295b4ee UPSTREAM: <carry>: openshift: Extend makefile with 'make goimports' target
072f7d777 UPSTREAM: <carry>: openshift: invalid delete ok
b2bf995e2 UPSTREAM: <carry>: openshift: Remove vendored drain lib
6227a5292 UPSTREAM: <carry>: openshift: Use native drain lib
bd4f0ba46 UPSTREAM: <carry>: openshift: remove paufantom from repository owners
2fbb225bc UPSTREAM: <carry>: openshift: Add files generated by `make dep-ensure`
4019c45f0 UPSTREAM: <carry>: openshift: Copy drain lib from openshift/kubernetes-drain and make it embedded
f8de78af8 UPSTREAM: <carry>: openshift: Read machine additional printer columns from annotations/labels
5de12103f UPSTREAM: <953>: openshift: Allow to use foregroundDeletion for MachineDeployments and MachineSets
72ebbaa04 UPSTREAM: <carry>: openshift: vendor update kubernetes-drain
67da5afc0 UPSTREAM: <carry>: openshift: Remove node controller from manager
046d74a3b UPSTREAM: <carry>: openshift: Update sigs.k8s.io/controller-runtime to release-2.0
e911af77e UPSTREAM: <carry>: openshift: regen clientset, bazel and CRDs
fdabfb108 UPSTREAM: <carry>: openshift: Alter code to accept updated sigs.k8s.io/controller-runtime@master
5b3271fa1 UPSTREAM: <carry>: openshift: Bump k8s to 1.14.1
a7df35547 UPSTREAM: <carry>: openshift: Ensure delete continues w/o node
b5b707e02 UPSTREAM: <896>: openshift: Add missing namespace to Get function
60850c99d UPSTREAM: <914>: openshift: Add support for passing namespace cmdline flag to the manager (#914)
b07024dd1 UPSTREAM: <carry>: openshift: Update README to reflect downstream dev
df5cff5fb UPSTREAM: <carry>: openshift: Remove cluster from machine.openshift.io
b41075de9 UPSTREAM: <carry>: openshift: Drop ProviderSpec.ValueFrom field
5343926d0 UPSTREAM: <carry>: openshift: Drop machine.status.conditions field
1e81530ea UPSTREAM: <carry>: openshift: Drop machine.status.versions field
e739b5bf1 UPSTREAM: <carry>: openshift: Drop ConfigSource field
2de8bf47c UPSTREAM: <carry>: openshift: Drop machine.spec.versions field
eba790fde UPSTREAM: <carry>: openshift: Ensure drain fail is requeued w/ delay
981822651 UPSTREAM: <871>: openshift: Fix argument order in error message for missing label in Machine object
430a5038b UPSTREAM: <carry>: openshift: validate machines with openshift specific constrains
2364fbe37 UPSTREAM: <905>: openshift: Clarify log message for machine-controller isDeleteAllowed
1950a39fc UPSTREAM: <carry>: openshift: drop machinedeployment
581679fb0 UPSTREAM: <880>: openshift: Record machine sync error event
4210030dc UPSTREAM: <carry>: openshift: Switch back to go 1.11.5
7c3040204 UPSTREAM: <carry>: openshift: Switch back to older version of bazel
920ef5387 UPSTREAM: <carry>: openshift: create git history verification script
bd9f034d1 UPSTREAM: <carry>: openshift: increase unit test timeout
131e92699 UPSTREAM: <759>: openshift: config: Adjust to new version of kustomize.
b2429cb5c UPSTREAM: <carry>: openshift: Machine controller: drain node before machine deletion
77fa8fa94 UPSTREAM: <carry>: openshift: Update import path to reflect github/openshift
d0fb90c2d UPSTREAM: <carry>: openshift: Sort machines before syncing
c745a34a0 UPSTREAM: <carry>: openshift: Validate machineSet before reconciliation
0533a9fef UPSTREAM: <carry>: openshift: Update config files for machine API
02995f3b8 UPSTREAM: <carry>: openshift: Run make generate after adding machine API
69a171ee4 UPSTREAM: <carry>: openshift: Mirror cluster.k8s.io/v1alpha1 into machine.openshift.io/v1beta1
e023562b9 UPSTREAM: <carry>: openshift: change ownership
712686dd6 UPSTREAM: <carry>: openshift: Update README to reflect downstream dev
a5c241a4a UPSTREAM: <905>: openshift: Clarify log message for machine-controller isDeleteAllowed
fa74913c1 UPSTREAM: <carry>: openshift: drop machinedeployment
29fee0a9e Release 0.1.0 (#861)
3f8a02c5c UPSTREAM: <carry>: openshift: create git history verification script
8b6a416a1 UPSTREAM: <carry>: openshift: increase unit test timeout
f26b1515b UPSTREAM: <759>: openshift: config: Adjust to new version of kustomize.
eaaebe5a6 UPSTREAM: <carry>: openshift: Update deps
39a5baaed UPSTREAM: <carry>: openshift: Machine controller: drain node before machine deletion
0ca063774 UPSTREAM: <809>: openshift: Delete node on machine deletion
3fc0ac858 UPSTREAM: <carry>: openshift: Allow to record machine update error
0c3e884db UPSTREAM: <carry>: openshift: Update import path to reflect github/openshift
6f37b1942 UPSTREAM: <carry>: openshift: Sort machines before syncing
30ba4a768 UPSTREAM: <carry>: openshift: Validate machineSet before reconciliation
57d164df6 UPSTREAM: <carry>: openshift: Delete annotated machines first when scaling down
2c1f1d0aa UPSTREAM: <carry>: openshift: Use RevisionVersion field instead of CreationTimestamp to decide which MS is new/old
8851abbf2 UPSTREAM: <carry>: openshift: Update config files for machine API
33aa094a9 UPSTREAM: <carry>: openshift: Run make generate after adding machine API
5714bfeca UPSTREAM: <carry>: openshift: Mirror cluster.k8s.io/v1alpha1 into machine.openshift.io/v1beta1
28d07a68a Update bazel rules-go (#714)
45e198f74 UPSTREAM: <carry>: openshift: change ownership
```

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
process looks good to me

**Comment by elmiko** [comment]
should we carry a commit to adjust all these owners files?

**Comment by alexander-demicev** [comment]
@elmiko the last carry commit does it

**Comment by lobziik** [comment]
@alexander-demichev remove OWNER_ALIASES please. Seems you did not include it :)

**Comment by elmiko** [comment]
> @elmiko the last carry commit does it

perfect, i was mostly reacting to https://github.com/openshift/cluster-api/pull/143#issuecomment-922928720

**Comment by JoelSpeed** [comment]
We will want to introduce a carry commit that removes the `.github` folder. We don't need or want the workflows that are defined upstream and they'll cause noise here

**Comment by JoelSpeed** [comment]
We seem to have no CI reporting on this repo at the moment, has this broken the status checks?

**Comment by alexander-demicev** [comment]
@JoelSpeed the CI is not configured right now for master branch, I'd like to merge the rebase and make sure that `e2e-aws` passes here https://github.com/openshift/release/pull/22081

**Comment by JoelSpeed** [comment]
@alexander-demichev There are required status checks on this repo, if the CI was recently removed then we need to somehow clear those checks else we won't be able to merge. Was the CI recently removed?

**Pull request merged**
